version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:3.2.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://kafka:9092
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_PORT: 9010
    depends_on: [zookeeper]

  jolokia-proxy:
    image: fvigotti/jolokia-proxy
    ports:
    - 8080:8080

  telegraf:
    image: quay.io/nordstrom/telegraf:1.3.0-1
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf

  telepath:
    build:
      context: .
      dockerfile: ./etc/Dockerfile.dev
    ports:
    - 8089:8089
    command:
    - "-brokers=kafka:9092"
    - "-log.level=debug"
    restart: on-failure
    depends_on: [kafka]

