version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - 2181:2181
    logging:
      driver: none

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: plaintext://kafka:9092
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_PORT: 9010
    logging:
      driver: none
    depends_on: [zookeeper]

  jolokia-proxy:
    image: fvigotti/jolokia-proxy
    ports:
    - 8080:8080
    logging:
      driver: none

  telegraf:
    image: quay.io/nordstrom/telegraf:1.4.0-1
    volumes:
    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf
    - ./etc/ca.pem:/var/private/ca.pem

  telepath:
    build:
      context: .
      dockerfile: ./etc/Dockerfile.dev
    ports:
    - 8089:8089
    - 8090:8090
    command:
    - "-kafka.brokers=kafka:9092"
    - "-log.level=debug"
    - "-log.format=text"
    - "-http.addr=:8089"
    - "-http.enabled=true"
    - "-https.addr=:8090"
    - "-https.enabled=true"
    - "-https.certificate=/var/private/server.pem"
    - "-https.key=/var/private/server-key.pem"
    - "-auth.enabled=true"
    - "-auth.username=writer"
    - "-auth.password=paperback"
    - "-kafka.version=V0_11_0_0"
    volumes:
    - ./etc/ca.pem:/var/private/ca.pem
    - ./etc/server.pem:/var/private/server.pem
    - ./etc/server-key.pem:/var/private/server-key.pem
    depends_on: [kafka]

